### ISSUE TITLE
cont values should be hardcoded

### ISSUE THREAD

**Issue by Dustin-Ray** [carolinenajwa/ed448-crypto-suite#1]
https://github.com/carolinenajwa/ed448-crypto-suite/blob/0b544f78d3c49b81ed01279658ed5dc0b5b0c013/Ed448-master/src/Ed448Points.java#L17

it is much better for performance to use a full precision calculator and actually hard code this value instead of computing it every time you need it:

that value should be:

```
726838724295606890549323807888004534353641360687318060281490199180612328166730772686396383698676545930088884461843637361053498018365439
```

and then even better is to just store it as hex because it is faster and more efficient to parse:

```
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```

**Comment by carolinedotxyz** [comment]
resolved
