### ISSUE TITLE
Scalar multiplication leaks private key

### ISSUE THREAD

**Issue by Dustin-Ray** [carolinenajwa/ed448-crypto-suite#2]
https://github.com/carolinenajwa/ed448-crypto-suite/blob/0b544f78d3c49b81ed01279658ed5dc0b5b0c013/Ed448-master/src/Ed448Points.java#L121

the else branch of this loop leaks the secret key used in multiplication:
![image](https://github.com/carolinenajwa/ed448-crypto-suite/assets/40841027/0198547f-5409-44d1-b46e-a839959f3b07)

A more secure implementation could use a [ladder](https://en.wikipedia.org/wiki/Elliptic_curve_point_multiplication):

```java
while (idx >= 0) {
    if (theS.testBit(idx--)) {
        r0 = r0.add(r1);
        r1 = r1.add(r1);
    } else { // constant operations performed 
        r1 = r0.add(r1);
        r0 = r0.add(r0);
    }
}
```

![image](https://github.com/carolinenajwa/ed448-crypto-suite/assets/40841027/2c333c99-c574-4357-a11c-6e8feea23fb8)

**Comment by carolinedotxyz** [comment]
Resolved, thanks!
